import type { NextPage } from 'next';
import Head from 'next/head';
import styles from '../styles/Home.module.css';

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Leif Westerlind's Dynamic Portfolio</title>
        {/*
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        */}
      </Head>

      <h1>Let's build an AWESOME portfolio!</h1>
    </div>
  )
};

export default Home;
